### ISSUE TITLE
URI notation for in-bag and ex-bag referencing 

### ISSUE THREAD

**Issue by yrad** [UTS-eResearch/datacrate#12]
Other packaging specifications privilege absolute URI notation for in-bag and ex-bag referencing:

- bag://bag-name/data/resource.xml

 [Data Conservancy Packaging Specification](http://dataconservancy.github.io/dc-packaging-spec/dc-packaging-spec-1.0.html#a3.2.3)

- file://metadata/descriptive/EAD.xml

[e-ARK draft Common Specification for Archival Packages](http://www.eark-project.com/resources/specificationdocs)

Otherwise, they say, a relative URI MUST be interpreted as being relative to the bag URI or document containing it. A NULL URI is interpreted the same way. 

I’d assumed this interpretation of relative links was normal and the absolute notation wasn’t necessary. E-ARK and Data Conservancy’s spec stresses that this notation scheme “allows bag resources to be addressed independent of its location on the filesystem… platform being used … bag’s serialized form”. I can dig that, but is this something that DataCrate needs to declare? Is this notation built-in to RDF schema or otherwise implied? Should it be possible to refer to a file OR directory from within or outside the bag using an identifier prefix? Presumably, but how would I manage that? Can the same assumptions be made for the DataCite XML?

This functionality is important if the spec supports bags with “holes”, where a bag can be pulled together from an aggregate or subset of distributed files or bags or things.

**Comment by ptsefton** [comment]
I think that the relative reference I've used should be OK without introducing any more complexity.
