### ISSUE TITLE
Inconsistency in Organizations microdocument

### ISSUE THREAD

**Issue by ThomasJejkal** [UTS-eResearch/datacrate#13]
In the **Organizations** expample the resource type is given as

typeof='schema:CreativeWork http://schema.org/Organization'

whereas the **Conventions** section states, that types and properties '[...]are be expressed as full URIs[...]to enable snippets of DataCrate markup to be copied an pasted without losing context'.

The same applies to the **Funding and grants** and **Equipment** examples.

Furthermore, I was wondering whether types like _http://schema.org:CreativeWork_ shouldn't be _http://schema.org/CreativeWork_?

**Comment by ptsefton** [comment]
No longer relevant.
