### ISSUE TITLE
Consider using embedded json-ld rather than RDFa + redundant CATALOG.json 

### ISSUE THREAD

**Issue by eocarragain** [UTS-eResearch/datacrate#14]
See https://twitter.com/eocarragain/status/940220166201372672

Opening a ticket for easier discussion.

**Comment by ptsefton** [comment]
Done in v0.2 - not sure if embedding is done correctly tho

**Comment by ptsefton** [comment]
Actually, there is a still a redundant CATALOG.json file for convenience, but the RDFa has been removed from the spec.
