### ISSUE TITLE
Check forward compatibility with BagIt V1.0

### ISSUE THREAD

**Issue by librarydatacarpentry** [UTS-eResearch/datacrate#34]
[BagIt spec](https://www.rfc-editor.org/info/rfc8493) `1.0` introduces a notable change from `0.97`, requiring every payload file to be listed in **every** payload manifest. Older versions of BagIt allowed payload files to be listed in just one of the manifests.

Discussion [here](https://github.com/LibraryOfCongress/bagit-spec/issues/2), and [here](https://groups.google.com/forum/#!searchin/digital-curation/bagit|sort:date/digital-curation/wQDO5Trmpqc/wirldA5BAgAJ).

> For BagIt 1.0, every payload file MUST be listed in every payload manifest.  Older versions of BagIt allowed payload files to be listed in just one of the manifests.

It doesn't look like this is an issue for _DataCrate_ but it's worth keeping in mind for [mixed checksum content](https://github.com/fair-research/bdbag/issues/27). It'd be worth checking the [other small changes](https://github.com/jkunze/bagitspec/pull/19) when we get a chance.

**Comment by yrad** [comment]
Whoops, posted issue #34 with a legacy account.

**Comment by ptsefton** [comment]
Closing this as it should not be an issue - but thanks @yrad.
